[package]
name = "account-vault-app"
version = "0.1.0"
description = "Desktop vault for account credentials"
authors = ["phumoonlight"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "account_vault_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chacha20poly1305 = "0.11.0"
thiserror = "2.0.21"
zeroize = { version = "1.9.0", features = ["derive"] }
uuid = { version = "1.27.0", features = ["v4"] }
keyring = "4.2.0"
tauri-plugin-dialog = "2"
argon2 = "0.6.0"
arboard = { version = "3.6.1", default-features = false }


# Read the optimization guideline for more details: https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true

[dev-dependencies]
tempfile = "3.27.0"

[profile.dev.package.chacha20poly1305]
opt-level = 3

[profile.dev.package.argon2]
opt-level = 3
